# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
<<<<<<< HEAD
  vmImage: 'ubuntu-latest'

steps:
=======
  name: 'MyAgentSelfHosted'
  vmImage: 'demoselfhostedagent'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: 
>>>>>>> db2775719447163e85d06f56cf1a15ac3737057d
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--output $(Build.BinariesDirectory)/publish_output --configuration Release'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
<<<<<<< HEAD

=======
>>>>>>> db2775719447163e85d06f56cf1a15ac3737057d
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'